name: build-myftp

on: [push]

env:
  DOTNET_VERSION: '6.x'

jobs:
  build:
    env: 
      project-name: MyFTP
    
    name: build-${{matrix.os}}-${{env.project-name}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: NuGet Restore
      run: nuget restore "$project-name"

    - name: Build
      run: dotnet build "$project-name"

    - name: Tests
      run: dotnet test "$project-name/$project-name.Tests"