name: build-myftp

on: [push]

env:
  DOTNET_VERSION: '6.x'
  project_name: MyFTP

jobs:
  build:   
    
    name: build-${{matrix.os}}-${{matrix.project_name}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        project_name: ['MyFTP']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: NuGet Restore
      run: nuget restore "${{matrix.project_name}}"

    - name: Build
      run: dotnet build "${{matrix.project_name}}"

    - name: Tests
      run: dotnet test "${{matrix.project_name}}/${{matrix.project_name}}.Tests"
