name: build-myftp

on: [push]

env:
  DOTNET_VERSION: '6.x'
  project_name: MyFTP

jobs:
  build:   
    
    name: build-${{matrix.os - project.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      project:
        name: MyFTP

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: NuGet Restore
      run: nuget restore "${{project_name}}"

    - name: Build
      run: dotnet build "${{project_name}}"

    - name: Tests
      run: dotnet test "${{project_name}}/${{project_name}}.Tests"